### ISSUE TITLE
Decoder 1.2.4: hparams = Nonetype, has no attribute 'problems' 

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#330]
Dear all,

After updating, I try to decode from a 1.2.3 v trained model and i got the following trace. It seems the new decoder doesn't recognise self-defined model in t2t_usr? The same command works in 1.2.3 for decoding as well. Would be great if someone could help. P.s. continue training on 1.2.3 trained model is perfectly fine.

python L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-decoder --t2t_usr=L:/python34_colman/projects/trans/usr/t2t_usr --data_dir=L:/python34_colman/projects/trans/t2t_data --problems=translate_enzh_un_characters_rev   --model=transformer --hparams_set=tier_transformer_base_single_gpu --output_dir=L:/python34_colman/projects/trans/t2t_train/translate_enzh_un_characters_rev/v2/transformer-tier_transformer_base_single_gpu   --decode_hparams="beam_size=4,alpha=0.6,use_last_position_only=True" --decode_from_file=L:/python34_colman/projects/trans/t2t_data/UNv1.0.devset.en
INFO:tensorflow:Importing user module t2t_usr from path L:/python34_colman/projects/trans/usr
INFO:tensorflow:Creating experiment, storing model files in L:/python34_colman/projects/trans/t2t_train/translate_enzh_un_characters_rev/v2/transformer-tier_transformer_base_single_gpu
Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-decoder", line 99, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-decoder", line 83, in main
    run_config=trainer_utils.create_run_config(output_dir))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 183, in create_experiment_components
    add_problem_hparams(hparams, FLAGS.problems)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 235, in add_problem_hparams
    hparams.problems = []
AttributeError: 'NoneType' object has no attribute 'problems'

**Comment by colmantse** [comment]
The problem disappeared after retraining in 1.2.4
